# 《人工智能编程基础》上机实验 - NumPy实践


**注意：只应该修改"_____"部分的内容，其他部分不应该，也不需要修改**


## 练习 N1：创建 NumPy 数组

**要求：** 根据提示使用不同的 NumPy 函数创建数组。

**需要填写的知识点：**
- `np.array(list)`：将基础的 Python 列表转换成 NumPy 数组。
- `np.arange(start, stop)`：创建等差数列数组，遵循左闭右开区间 $[start, stop)$。
- `np.zeros(shape)`：创建全零数组，`shape` 通常需要传入一个元组，例如 $(行数, 列数)$。

In [1]:
# ============================================================
# 练习 N1：创建 NumPy 数组
# ============================================================
# 目标：掌握基础的数组创建方法
# ============================================================

import numpy as np  # 导入 numpy 库，约定别名为 np

# ① 将 Python 列表转换成数组
data_list = [10, 20, 30, 40]
# 请在 _____ 处填入对应的库别名和函数名
arr_from_list = np.array(data_list)
print("从列表创建的数组:\n", arr_from_list)

# ② 创建 0 到 9 的连续一维数组（不包含 10）
# 请在 _____ 处填入正确的函数名和结束值
arr_arange = np.arange(0, 10)
print("arange 创建的连续数组:\n", arr_arange)

# ③ 创建一个 2 行 3 列的全零矩阵
# 请在 _____ 处填入表示形状尺寸的元组 (行, 列)
arr_zeros = np.zeros((2, 3))
print("2x3 全零矩阵:\n", arr_zeros)


从列表创建的数组:
 [10 20 30 40]
arange 创建的连续数组:
 [0 1 2 3 4 5 6 7 8 9]
2x3 全零矩阵:
 [[0. 0. 0.]
 [0. 0. 0.]]


---
## 练习 N2：数组的标量与元素级运算

**要求：** 对 NumPy 数组进行基础的数学运算。NumPy 支持直接对整个数组进行批量运算，例如 $y_i = x_i + 5$。

**需要填写的知识点：**
- 数组与标量运算：`arr * 2` 会将数组中的每个元素都乘以 2。
- 数组间相互运算：要求形状相同，对应位置的元素直接进行加减乘除。
- 通用函数（ufunc）：如开平方根 `np.sqrt(x)`。

In [2]:
# ============================================================
# 练习 N2：数组的运算
# ============================================================

import numpy as np

arr = np.array([1, 4, 9, 16])

# ① 标量运算：让 arr 中的每个元素都加上 5
# 请在 _____ 处填入正确的操作符和数值
add_result = arr + 5
print("每个元素加 5:", add_result)

# ② 元素级运算：计算 arr 中每个元素的平方根
# 请在 _____ 处填入 numpy 求平方根的通用函数名
sqrt_result = np.sqrt(arr)
print("每个元素的平方根:", sqrt_result)


每个元素加 5: [ 6  9 14 21]
每个元素的平方根: [1. 2. 3. 4.]


---
## 练习 N3：数组的索引与切片

**要求：** 提取一维和二维数组中指定位置的数据。

**需要填写的知识点：**
- 一维切片：`arr[start:end]`，遵循左闭右开。
- 二维索引：`arr[row_index, col_index]`，索引从 $0$ 开始计数。
- 提取整列：`arr[:, col_index]`，`:` 表示选中该维度的全部数据。

In [3]:
# ============================================================
# 练习 N3：索引与切片
# ============================================================

import numpy as np

arr_1d = np.array([10, 20, 30, 40, 50, 60])
matrix_2d = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])

# ① 提取一维数组的第 2 到 第 4 个元素 (即数值 30, 40, 50)
# 请在 _____ 处填入正确的起始和结束索引（注意索引从 0 开始计数）
slice_1d = arr_1d[2 : 5]
print("截取的一维切片:", slice_1d)

# ② 提取二维矩阵中第 2 行、第 3 列的单个元素 (即数值 6)
# 请在 _____ 处填入正确的行索引和列索引
element = matrix_2d[1, 2]
print("特定的单个元素:", element)

# ③ 提取二维矩阵的第 1 列所有数据 (即数值 1, 4, 7)
# 请在 _____ 处填入正确的切片符号和列索引
column_data = matrix_2d[:, 0]
print("第一列所有数据:", column_data)


截取的一维切片: [30 40 50]
特定的单个元素: 6
第一列所有数据: [1 4 7]


---
## 练习 N4：布尔索引与条件筛选

**要求：** 使用布尔条件从数组中筛选出满足条件的元素。这是数据分析中最常用的操作之一。

**需要填写的知识点：**
- 布尔数组：对数组使用比较运算符（`>`, `<`, `>=`, `<=`, `==`）会返回一个同形状的布尔数组（`True`/`False`）。
  - 例如 `np.array([1, 5, 3]) > 2` → `[False, True, True]`
- 布尔索引：将布尔数组放入方括号 `[]` 中，可以筛选出对应位置为 `True` 的元素。
  - 例如 `arr[arr > 2]` → 只保留大于 2 的元素
- `np.where(condition)`：返回满足条件的元素的**索引位置**（而非元素值本身）。

In [4]:
# ============================================================
# 练习 N4：布尔索引与条件筛选
# ============================================================
# 目标：掌握布尔索引筛选数据的方法
# ============================================================

import numpy as np

# 一组学生的考试成绩
scores = np.array([58, 92, 75, 43, 88, 67, 95, 51, 80, 72])

# ① 生成布尔数组：判断每个成绩是否及格（>= 60）
# 请在 _____ 处填入比较运算符和数值
passed = scores >= 60
print("是否及格:", passed)
# 预期输出: [False  True  True False  True  True  True False  True  True]

# ② 使用布尔索引筛选出所有及格的成绩
# 请在 _____ 处填入正确的布尔数组变量名
passed_scores = scores[passed]
print("及格的成绩:", passed_scores)
# 预期输出: [92 75 88 67 95 80 72]

# ③ 找出所有不及格成绩所在的索引位置
# 请在 _____ 处填入函数名和正确的条件表达式
fail_indices = np.where(scores < 60)
print("不及格的索引位置:", fail_indices)
# 预期输出: (array([0, 3, 7]),)

是否及格: [False  True  True False  True  True  True False  True  True]
及格的成绩: [92 75 88 67 95 80 72]
不及格的索引位置: (array([0, 3, 7]),)


---
## 练习 N5：数组排序

**要求：** 对数组进行排序，并找到最大值、最小值对应的索引。

**需要填写的知识点：**
- `np.sort(arr)`：返回排序后的**新数组**（原数组不变），默认从小到大排列。
- `np.argsort(arr)`：返回排序后元素在**原数组中的索引**。
  - 例如 `np.argsort([30, 10, 20])` → `[1, 2, 0]`（10 在原位置 1，20 在原位置 2，30 在原位置 0）
- `np.argmax(arr)`：返回数组中**最大值**的索引。
- `np.argmin(arr)`：返回数组中**最小值**的索引。

In [5]:
# ============================================================
# 练习 N5：数组排序
# ============================================================
# 目标：掌握排序函数及索引查找
# ============================================================

import numpy as np

# 5 位选手的比赛得分
players = ["Alice", "Bob", "Cindy", "David", "Eva"]
scores = np.array([78, 95, 63, 88, 71])

# ① 将成绩从小到大排序（不修改原数组）
# 请在 _____ 处填入排序函数名
sorted_scores = np.sort(scores)
print("排序后的成绩:", sorted_scores)
# 预期输出: [63 71 78 88 95]

# ② 获取排序后元素在原数组中的索引
# 请在 _____ 处填入返回排序索引的函数名
sort_indices = np.argsort(scores)
print("排序索引:", sort_indices)
# 预期输出: [2 4 0 3 1]（即 Cindy 最低, Bob 最高）

# ③ 找出最高分选手的索引，并输出其名字
# 请在 _____ 处填入求最大值索引的函数名
best_idx = np.argmax(scores)
print("最高分选手:", players[best_idx], "得分:", scores[best_idx])
# 预期输出: 最高分选手: Bob 得分: 95

# ④ 找出最低分选手的索引，并输出其名字
# 请在 _____ 处填入求最小值索引的函数名
worst_idx = np.argmin(scores)
print("最低分选手:", players[worst_idx], "得分:", scores[worst_idx])
# 预期输出: 最低分选手: Cindy 得分: 63

排序后的成绩: [63 71 78 88 95]
排序索引: [2 4 0 3 1]
最高分选手: Bob 得分: 95
最低分选手: Cindy 得分: 63


---
## 练习 N6：数组拼接与拆分

**要求：** 将多个数组合并成一个更大的数组，掌握纵向拼接和横向拼接的区别。

**需要填写的知识点：**
- `np.concatenate([a, b])`：将多个**一维**数组首尾相连拼接成一个更长的数组。
- `np.vstack([a, b])`：**纵向堆叠**（Vertical Stack），将数组按行上下拼接。
  - 要求每个数组的**列数相同**。
- `np.hstack([a, b])`：**横向堆叠**（Horizontal Stack），将数组按列左右拼接。
  - 要求每个数组的**行数相同**。
- `.shape` 属性：查看数组的形状，返回元组 `(行数, 列数)`。

In [6]:
# ============================================================
# 练习 N6：数组拼接与拆分
# ============================================================
# 目标：掌握数组的拼接操作
# ============================================================

import numpy as np

# ① 一维数组拼接
arr_a = np.array([1, 2, 3])
arr_b = np.array([4, 5, 6])
# 请在 _____ 处填入拼接函数名
arr_concat = np.concatenate([arr_a, arr_b])
print("一维拼接:", arr_concat)
# 预期输出: [1 2 3 4 5 6]

# ② 纵向堆叠（上下拼接）
# 期中考试和期末考试成绩（3 名学生）
midterm = np.array([[80, 90, 85]])    # 1 行 3 列
final   = np.array([[88, 78, 92]])    # 1 行 3 列
# 请在 _____ 处填入纵向堆叠的函数名
all_scores = np.vstack([midterm, final])
print("纵向堆叠:\n", all_scores)
print("形状:", all_scores.shape)
# 预期输出:
# [[80 90 85]
#  [88 78 92]]
# 形状: (2, 3)

# ③ 横向堆叠（左右拼接）
# 学生姓名对应的语文和数学成绩
chinese = np.array([[90], [85], [78]])   # 3 行 1 列
math    = np.array([[88], [92], [80]])   # 3 行 1 列
# 请在 _____ 处填入横向堆叠的函数名
all_subjects = np.hstack([chinese, math])
print("横向堆叠:\n", all_subjects)
print("形状:", all_subjects.shape)
# 预期输出:
# [[90 88]
#  [85 92]
#  [78 80]]
# 形状: (3, 2)

一维拼接: [1 2 3 4 5 6]
纵向堆叠:
 [[80 90 85]
 [88 78 92]]
形状: (2, 3)
横向堆叠:
 [[90 88]
 [85 92]
 [78 80]]
形状: (3, 2)


---
## 练习 N7：数学运算与广播

**要求：** 对数组进行元素级算术运算，以及数组与标量之间的广播运算。

**需要填写的知识点：**

- **元素级运算**：两个形状相同的数组直接用 `+`、`-`、`*`、`/` 即可逐元素计算
- **广播（Broadcasting）**：数组与单个数值（标量）运算时，标量自动扩展到与数组相同大小
  - 例：`arr * 2` 将数组每个元素都乘以 2
- **常用数学函数**：
  - `np.sqrt(arr)` 逐元素开平方根
  - `np.abs(arr)` 逐元素取绝对值
  - `np.exp(arr)` 逐元素计算 e 的幂次（e^x）
  - `np.log(arr)` 逐元素计算自然对数（ln x）

In [7]:
# ============================================================
# 练习 N7：数学运算与广播
# ============================================================
# 目标：掌握数组的元素级运算和广播机制
# 要求：加减乘除、标量广播、常用数学函数
# ============================================================

import numpy as np

# ① 两数组的元素级运算
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

# 请在 _____ 处填入正确的运算符
add_result = a + b          # 对应元素相加
print("a + b =", add_result)    # 期望输出：[11 22 33 44 55]

mul_result = a * b          # 对应元素相乘
print("a * b =", mul_result)    # 期望输出：[10 40 90 160 250]

# ② 标量广播运算
# 请在 _____ 处填入使每个元素乘以 3 的表达式
scaled = a * 3
print("a * 3 =", scaled)        # 期望输出：[ 3  6  9 12 15]

# 请在 _____ 处填入使每个元素加 100 的表达式
shifted = b + 100
print("b + 100 =", shifted)     # 期望输出：[110 120 130 140 150]

# ③ 常用数学函数
vals = np.array([1, 4, 9, 16, 25])

# 请在 _____ 处填入计算开平方根的函数名
roots = np.sqrt(vals)
print("平方根：", roots)        # 期望输出：[1. 2. 3. 4. 5.]

neg_vals = np.array([-3, -1, 0, 2, 5])
# 请在 _____ 处填入计算绝对值的函数名
abs_vals = np.abs(neg_vals)
print("绝对值：", abs_vals)     # 期望输出：[3 1 0 2 5]

a + b = [11 22 33 44 55]
a * b = [ 10  40  90 160 250]
a * 3 = [ 3  6  9 12 15]
b + 100 = [110 120 130 140 150]
平方根： [1. 2. 3. 4. 5.]
绝对值： [3 1 0 2 5]


---
## 练习 N8：聚合统计与 Axis 参数

**要求：** 使用 NumPy 内置的统计函数，并理解多维数组的轴 (`axis`) 概念。

**需要填写的知识点：**
- `np.sum()`：求和，`np.mean()`：求均值即 $\mu = \frac{1}{N}\sum_{i=1}^{N} x_i$。
- 对于二维数组，指定方向非常重要：
  - `axis=0`：沿着行的方向垂直往下计算（即 **计算每一列的结果**）。
  - `axis=1`：沿着列的方向水平向右计算（即 **计算每一行的结果**）。

In [8]:
# ============================================================
# 练习 N8：聚合函数与 axis 参数
# ============================================================

import numpy as np

scores = np.array([[80, 90, 85],     # 学生A的三门课成绩
                   [70, 75, 80],     # 学生B的三门课成绩
                   [95, 95, 100]])   # 学生C的三门课成绩

# ① 求解全体成绩的平均分
# 请在 _____ 处填入求均值的函数名
overall_mean = np.mean(scores)
print("全体平均分:", overall_mean)

# ② 求解每门课（每一列）的最高分
# 请在 _____ 处填入求最大值的函数名，以及正确的 axis 轴取值(0 或 1)
max_by_subject = np.max(scores, axis=0)
print("每门课的最高分:", max_by_subject)


全体平均分: 85.55555555555556
每门课的最高分: [ 95  95 100]


---
## 练习 N9：更改数组维度（进阶）

**要求：** 将一维数组转换为多维数组。

**需要填写的知识点：**
- `arr.reshape(rows, cols)`：改变数组的形状。要求转换前后的总元素数量必须一致，必须满足公式：
  
  $$N_{总数} = 行数 \times 列数$$
  
- 在 `reshape` 中，可以使用 `-1` 作为占位符，NumPy 会根据其他维度的尺寸自动推导未知维度的长度。

In [9]:
# ============================================================
# 练习 N9：更改数组维度
# ============================================================

import numpy as np

# 生成从 1 到 12 的一维数组（共 12 个元素）
arr_12 = np.arange(1, 13)

# ① 将该一维数组改为 3 行 4 列的二维数组
# 请在 _____ 处填入期望的行数和列数
reshaped_3x4 = arr_12.reshape(3, 4)
print("3行4列矩阵:\n", reshaped_3x4)

# ② 使用自动推导转换形状
# 如果我们要求固定为 2 行，列数让 NumPy 去自动计算
# 请在第一个 _____ 填入行数，第二个 _____ 填入自动推导占位符(-1)
reshaped_auto = arr_12.reshape(2, -1)
print("2行N列（自动推导）:\n", reshaped_auto)


3行4列矩阵:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2行N列（自动推导）:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


---
## 练习 N10：随机数与矩阵运算（进阶）

**要求：** 使用 NumPy 生成随机数组，并完成转置和矩阵乘法运算。

**需要填写的知识点：**
- `np.random.seed(n)`：设置随机种子，确保每次运行生成相同的随机数（便于调试和评分）。
- `np.random.randint(low, high, size)`：生成 $[low, high)$ 范围内的随机整数数组。
  - 例如 `np.random.randint(1, 10, size=(2, 3))` → 生成 2 行 3 列、值在 1~9 之间的随机整数矩阵
- `arr.T`：矩阵**转置**，即行列互换。形状 $(m, n)$ 的矩阵转置后变为 $(n, m)$。
- `np.dot(A, B)` 或 `A @ B`：矩阵乘法。要求 A 的列数 = B 的行数，即 $(m, k) \times (k, n) \rightarrow (m, n)$。

In [10]:
# ============================================================
# 练习 N10：随机数与矩阵运算（进阶）
# ============================================================
# 目标：掌握随机数生成、转置和矩阵乘法
# ============================================================

import numpy as np

# 设置随机种子，保证每次运行结果一致
np.random.seed(42)

# ① 生成一个 2 行 3 列的随机整数矩阵，值的范围在 1 到 9 之间
# 请在 _____ 处填入正确的函数名和 size 参数（元组）
A = np.random.randint(1, 10, size=(2, 3))
print("矩阵 A:\n", A)
print("A 的形状:", A.shape)

# ② 对矩阵 A 进行转置（行列互换），得到 3 行 2 列的矩阵
# 请在 _____ 处填入转置的属性名
A_T = A.T
print("A 的转置:\n", A_T)
print("转置后的形状:", A_T.shape)

# ③ 计算矩阵乘法：A × A_T
# A 的形状是 (2, 3)，A_T 的形状是 (3, 2)，结果形状应为 (2, 2)
# 请在 _____ 处填入矩阵乘法的函数名
result = np.dot(A, A_T)
print("A × A_T 的结果:\n", result)
print("结果形状:", result.shape)

矩阵 A:
 [[7 4 8]
 [5 7 3]]
A 的形状: (2, 3)
A 的转置:
 [[7 5]
 [4 7]
 [8 3]]
转置后的形状: (3, 2)
A × A_T 的结果:
 [[129  87]
 [ 87  83]]
结果形状: (2, 2)
